version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: python runbot.py
